3506 expressions tissues
opentargets/ontoform pull request #3
Opened 2024-10-25 09:06 UTC by remo87

This PR solves the tissue transformation specified in [3506](https://github.com/opentargets/issues/issues/3506)

- **agregar transformacion tissues**
- **Update code comments**

2024-10-25 11:12 UTC, javfg approved these changes

2024-10-25 11:13 UTC, javfg requested changes

2024-10-25 11:13 UTC, javfg commented on src/ontoform/transformers/expressions_tissue.py
> +import polars.selectors as cs
I think that import is unused

2024-10-25 15:01 UTC, javfg approved these changes

2024-10-25 15:03 UTC, merged

2024-11-25 16:18 UTC, addramir commented
This is listed as issue in the release board. Should I remove it from there?

2024-11-25 16:33 UTC, javfg commented
Go ahead!